// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZJO60dbwg3slyI14ecfqtvad-9piaQpc',
    appId: '1:169271304140:web:651397ca6ef23cfe4dc769',
    messagingSenderId: '169271304140',
    projectId: 'cbank-dd3d6',
    authDomain: 'cbank-dd3d6.firebaseapp.com',
    storageBucket: 'cbank-dd3d6.appspot.com',
    measurementId: 'G-54DEP2YGHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd03y8aTbPeHXac7J8g5i4BFJCUAt2Akg',
    appId: '1:169271304140:android:10fd9109d0a053fc4dc769',
    messagingSenderId: '169271304140',
    projectId: 'cbank-dd3d6',
    storageBucket: 'cbank-dd3d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmZN1Wy0PnaUSfx9HxBAixWs3r0ph3rmg',
    appId: '1:169271304140:ios:b272ed27f89fff7b4dc769',
    messagingSenderId: '169271304140',
    projectId: 'cbank-dd3d6',
    storageBucket: 'cbank-dd3d6.appspot.com',
    iosClientId: '169271304140-25t2m4e5l1h8hk0hfo7efa4peaiamhsi.apps.googleusercontent.com',
    iosBundleId: 'com.example.pii6',
  );
}
